import 'product.dart';

class Myproduct {
  static List<Product> allproducts = [
    ...Animeproduct,
    ...GameProduct,
    ...ShoesProduct,
    Product(
      id: 1,
      name: "Nike Air force1",
      price: 180.000,
      image: "images/Shoes/Nike Dunk low black.jpg",
      category: "Trending Now",
      description: "Nice 1",
      quantity: 1,
    ),
    Product(
      id: 2,
      name: "Nike Air force1",
      price: 180.000,
      image: "images/Shoes/Nike Dunk low Brow.jpg",
      category: "Trending Now",
      description: "Nice 1",
      quantity: 1,
    ),
    Product(
      id: 3,
      name: "Nike Air force1",
      price: 180.000,
      image: "images/Shoes/Nike Dunk low blue.jpg",
      category: "Trending Now",
      description: "Nice 1",
      quantity: 1,
    ),
    Product(
      id: 4,
      name: "Nike Air force1",
      price: 180.000,
      image: "images/Shoes/Nike Dunk low Orange.jpg",
      category: "Trending Now",
      description: "Nice 1",
      quantity: 1,
    ),
    Product(
      id: 5,
      name: "Nike Air force1",
      price: 180.000,
      image: "images/Shoes/Nike Dunk low Red.jpg",
      category: "Trending Now",
      description: "Nice 1",
      quantity: 1,
    ),
  ];

  static List<Product> Animeproduct = [
    Product(
      id: 1,
      name: "Gojo ",
      price: 180.000,
      image: "images/Anime/Jujutsu Gojo.jpg",
      category: "Trending Now",
      description: "Nice 1",
      quantity: 1,
    ),
    Product(
      id: 2,
      name: "Sukuna ",
      price: 180.000,
      image: "images/Anime/Jujutsu Sukuna.jpg",
      category: "Trending Now",
      description: "Nice 1",
      quantity: 1,
    ),
    Product(
      id: 3,
      name: "yuta ",
      price: 180.000,
      image: "images/Anime/Jujutsu yuta.jpg",
      category: "Trending Now",
      description: "Nice 1",
      quantity: 1,
    ),
    Product(
      id: 4,
      name: "Kilua ",
      price: 180.000,
      image: "images/Anime/Kilua.jpg",
      category: "Trending Now",
      description: "Nice 1",
      quantity: 1,
    ),
    Product(
      id: 5,
      name: "tobiotogiri ",
      price: 180.000,
      image: "images/Anime/tobiotogiri.jpg",
      category: "Trending Now",
      description: "Nice 1",
      quantity: 1,
    ),
  ];
  static List<Product> GameProduct = [
    Product(
      id: 1,
      name: "raiden ",
      price: 180.000,
      image: "images/game/Genhsin raiden.jpg",
      category: "Trending Now",
      description: "Nice 1",
      quantity: 1,
    ),
    Product(
      id: 2,
      name: "Yaemiko ",
      price: 180.000,
      image: "images/game/Genhsin Yaemiko.jpg",
      category: "Trending Now",
      description: "Nice 1",
      quantity: 1,
    ),
    Product(
      id: 3,
      name: "furina ",
      price: 180.000,
      image: "images/game/Genshin furina.jpg",
      category: "Trending Now",
      description: "Nice 1",
      quantity: 1,
    ),
    Product(
      id: 4,
      name: "hutao ",
      price: 180.000,
      image: "images/game/genshin hutao.jpg",
      category: "Trending Now",
      description: "Nice 1",
      quantity: 1,
    ),
    Product(
      id: 5,
      name: "skirk ",
      price: 180.000,
      image: "images/game/genshin skirk.jpg",
      category: "Trending Now",
      description: "Nice 1",
      quantity: 1,
    ),
  ];
  static List<Product> ShoesProduct = [
    Product(
      id: 1,
      name: "Nike Air force1",
      price: 180.000,
      image: "images/Shoes/Nike Dunk low black.jpg",
      category: "Trending Now",
      description: "Nice 1",
      quantity: 1,
    ),
    Product(
      id: 2,
      name: "Nike Air force1",
      price: 180.000,
      image: "images/Shoes/Nike Dunk low Brow.jpg",
      category: "Trending Now",
      description: "Nice 1",
      quantity: 1,
    ),
    Product(
      id: 3,
      name: "Nike Air force1",
      price: 180.000,
      image: "images/Shoes/Nike Dunk low blue.jpg",
      category: "Trending Now",
      description: "Nice 1",
      quantity: 1,
    ),
    Product(
      id: 4,
      name: "Nike Air force1",
      price: 180.000,
      image: "images/Shoes/Nike Dunk low Orange.jpg",
      category: "Trending Now",
      description: "Nice 1",
      quantity: 1,
    ),
    Product(
      id: 5,
      name: "Nike Air force1",
      price: 180.000,
      image: "images/Shoes/Nike Dunk low Red.jpg",
      category: "Trending Now",
      description: "Nice 1",
      quantity: 1,
    ),
  ];
}
